In [4]:
import numpy as np
import operator

In [2]:
b = np.array([[25, 15, -5], [15, 18, 0], [-5, 0, 11]])
b

array([[25, 15, -5],
       [15, 18,  0],
       [-5,  0, 11]])

In [5]:
import operator
def ref(matrix, subm = 0):
    # subm is used for recurion, it's the row and column number of the submatrix

    if len(matrix) == 0 or len(matrix[0]) == 0:
        return matrix

    if len(matrix) - subm <= 1 or len(matrix[0]) - subm <= 1:
        return matrix

    # handle case where entry being looked at is 0 and case where entire column is 0
    if matrix[subm][subm] == 0:
        for i in range(subm + 1, len(matrix)):
            if matrix[i][subm] != 0:
                matrix[subm], matrix[i] = matrix[i], matrix[subm]  # swap rows
                break
        else:  # if for loop never breaks (column is all zeros)
            return ref(matrix, subm + 1)

    # get zeros in entries below current leading entry
    for i in range(subm + 1, len(matrix)):
        # usage of map for operations on lists from https://stackoverflow.com/a/534914/18413833
        # faster than using list comprehension
        row_multiple = map((matrix[i][subm] / matrix[subm][subm]).__mul__, matrix[subm])
        matrix[i][:] = map(operator.sub, matrix[i], row_multiple)

    # repeat with next row and column
    return ref(matrix, subm + 1)

In [7]:
ref_b = np.array(ref([[25, 15, -5], [15, 18, 0], [-5, 0, 11]]))
ref_b

array([[25., 15., -5.],
       [ 0.,  9.,  3.],
       [ 0.,  0.,  9.]])

In [8]:
def u(ref):
  u = np.zeros((len(b), len(b)))

  for i in range(0, len(b)):
    for j in range(0, len(b)):
      u[i][j] = (ref[i][j] / (ref[i][i] ** 0.5))
  return u

In [14]:
u = u(ref_b)
u

array([[ 5.,  3., -1.],
       [ 0.,  3.,  1.],
       [ 0.,  0.,  3.]])

In [12]:
def transpose(temp):
  result =  np.zeros((len(b), len(b)))
  for i in range(0, len(b)):
    for j in range(0, len(b)):
      result[j][i] = temp[i][j]
  return result

In [15]:
u_t = transpose(u)
u_t

array([[ 5.,  0.,  0.],
       [ 3.,  3.,  0.],
       [-1.,  1.,  3.]])